import type { Tab } from './types';

export const content: Tab[] = [
    // ===== TAB 1: OVERVIEW =====
    {
        id: 'overview',
        label: 'Overview',
        hero: {
            title: 'Welcome to AI Foundations',
            subtitle: 'Your guided path to mastering AI. From complete beginner to confident practitioner.',
            videoUrl: 'https://www.youtube.com/embed/2ePf9rue1Ao',
        },
        sections: [
            {
                id: 'why-learn-ai',
                title: 'Why Learn AI Now?',
                intro: 'AI is transforming every industry. Understanding it is no longer optional - it is essential for career growth.',
                cards: [
                    {
                        id: 'ai-imperative',
                        type: 'alert',
                        alertType: 'important',
                        title: 'The AI Imperative',
                        content: 'By 2025, 97 million new roles will emerge adapted to human-machine collaboration. Those who understand AI will lead. Those who do not will follow.',
                        fullWidth: true,
                    },
                ],
            },
            {
                id: 'quick-wins',
                title: 'Your Quick Wins Today',
                intro: 'Start with these five actionable steps. Each one takes less than 10 minutes and builds your AI foundation.',
                centered: true,
                cards: [
                    {
                        id: 'quick-wins-carousel',
                        type: 'actionCarousel',
                        actionItems: [
                            {
                                title: 'Sign Up for Google Developer - Get $300 Free!',
                                description: 'Your gateway to free AI learning and cloud credits.',
                                details: [
                                    '35 free learning points every month for Google Skills courses',
                                    '$300 in Google Cloud credits valid for 90 days',
                                    'Access to Google Labs for experimental AI features',
                                    'Free skill badges to add to your LinkedIn profile',
                                ],
                                url: 'https://developers.google.com/',
                                buttonText: 'Sign Up Free',
                            },
                            {
                                title: 'Try Google AI Studio',
                                description: 'The fastest path from prompt to production with Gemini.',
                                details: [
                                    'Experiment with Gemini models instantly - no setup required',
                                    'Generate and test API keys for your projects',
                                    'Save and share your best prompts',
                                    'Export code directly to your applications',
                                ],
                                url: 'https://aistudio.google.com/',
                                buttonText: 'Launch AI Studio',
                            },
                            {
                                title: 'Explore NotebookLM',
                                description: 'Upload any document and have AI explain it to you.',
                                details: [
                                    'Upload PDFs, docs, or paste text for AI analysis',
                                    'Ask questions and get cited answers from your sources',
                                    'Generate summaries, outlines, and study guides',
                                    'Create AI-generated podcast discussions of your content',
                                ],
                                url: 'https://notebooklm.google.com/',
                                buttonText: 'Try NotebookLM',
                            },
                            {
                                title: 'Download Superwhisper',
                                description: 'Speak 3x faster than you type. Local, private, accurate.',
                                details: [
                                    'Average speaking speed: 150 WPM vs typing: 60-80 WPM',
                                    'Runs 100% locally on your Mac - nothing sent to the cloud',
                                    'Works in any app - emails, documents, code, messages',
                                    'Supports multiple languages and voice commands',
                                ],
                                url: 'https://superwhisper.com/',
                                buttonText: 'Download for Mac',
                            },
                            {
                                title: 'Take a 45-Minute Free Course',
                                description: 'Complete your first AI certification in under an hour.',
                                details: [
                                    'Introduction to Generative AI - official Google course',
                                    'Earn a skill badge for your LinkedIn profile',
                                    'Uses your free Google Developer learning points',
                                    'No coding required - perfect for beginners',
                                ],
                                url: 'https://www.cloudskillsboost.google/course_templates/536',
                                buttonText: 'Start Learning',
                            },
                        ],
                    },
                ],
            },
            {
                id: 'physical-reality',
                title: 'Understanding AI\'s Physical Reality',
                intro: 'Before diving into tools, understand what AI actually is and how it works.',
                cards: [
                    {
                        id: 'slide-physical',
                        type: 'slideViewer',
                        title: 'AI\'s Physical Reality',
                        pdfPath: '/slides/1. AI_s_Physical_Reality.pdf',
                    },
                ],
            },
            {
                id: 'learning-path',
                title: 'Your Learning Path',
                cards: [
                    {
                        id: 'path-callout',
                        type: 'callout',
                        title: 'Recommended Journey',
                        content: 'Start with Google Setup to get your accounts ready. Take the free courses to build foundations. Then explore tools and eventually pursue certifications for career advancement.',
                    },
                    {
                        id: 'ai-ml-dl',
                        type: 'text',
                        title: 'AI vs ML vs Deep Learning',
                        content: 'AI is the broad concept of machines performing tasks "smartly." Machine Learning is a subset where machines learn from data. Deep Learning uses neural networks with many layers. Generative AI (like ChatGPT, Gemini, Claude) is built on Deep Learning.',
                    },
                ],
            },
        ],
    },

    // ===== TAB 2: GOOGLE SETUP =====
    {
        id: 'google-setup',
        label: 'Google Setup',
        hero: {
            title: 'Set Up Your Google AI Workspace',
            subtitle: 'Google has SO much to offer. Let us unlock it all.',
            videoUrl: 'https://www.youtube.com/embed/sVj8_kHiguY',
        },
        sections: [
            {
                id: 'navigation-warning',
                title: 'Before You Begin',
                cards: [
                    {
                        id: 'google-warning',
                        type: 'alert',
                        alertType: 'warning',
                        title: 'Google Can Be Confusing',
                        content: 'Google\'s AI ecosystem is powerful but not always easy to navigate. They have many overlapping products with similar names. Do not worry - we will guide you through exactly what you need. Bookmark this page!',
                        fullWidth: true,
                    },
                ],
            },
            {
                id: 'developer-account',
                title: 'Step 1: Google Developer Account',
                intro: 'Your gateway to free learning and experimentation.',
                cards: [
                    {
                        id: 'why-developer',
                        type: 'callout',
                        title: 'Why Developer Account?',
                        content: 'Even if you are not a developer, this gives you 35 points per month for learning on Google Skills. Earn badges for your resume and access exclusive features in Google Labs - all for free!',
                    },
                    {
                        id: 'developer-links',
                        type: 'linksGrid',
                        title: 'Essential Links',
                        links: [
                            { label: 'Google Developer', url: 'https://developers.google.com/', description: 'Sign up for your developer account' },
                            { label: 'Google Skills', url: 'https://www.cloudskillsboost.google/', description: 'Earn badges with your 35 monthly points' },
                            { label: 'Google Labs', url: 'https://labs.google/', description: 'Experiment with cutting-edge AI' },
                        ],
                    },
                ],
            },
            {
                id: 'cloud-credits',
                title: 'Step 2: $300 Free Cloud Credits',
                intro: 'Google gives you $300 to experiment with their cloud services.',
                cards: [
                    {
                        id: 'credits-alert',
                        type: 'alert',
                        alertType: 'tip',
                        title: '90 Days to Spend Your Credits',
                        content: 'Your $300 credits expire in 90 days. Use them wisely! Great for experimenting with Gemini API, Vertex AI, and building real projects. Start small and scale up.',
                    },
                    {
                        id: 'credits-uses',
                        type: 'checklist',
                        title: 'What You Can Do With Credits',
                        checklistLinks: [
                            { label: 'Get a Gemini API key to use anywhere', url: 'https://aistudio.google.com/apikey' },
                            { label: 'Experiment with Vertex AI for ML projects', url: 'https://cloud.google.com/vertex-ai' },
                            { label: 'Generate videos with Veo 3', url: 'https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview' },
                            { label: 'Design UIs with Google Stitch', url: 'https://stitch.withgoogle.com/' },
                            { label: 'Run BigQuery for data analysis', url: 'https://cloud.google.com/bigquery' },
                        ],
                    },
                    {
                        id: 'cloud-link',
                        type: 'linksGrid',
                        title: 'Get Started',
                        links: [
                            { label: 'Google Cloud Console', url: 'https://console.cloud.google.com/', description: 'Sign up and claim your $300 credits' },
                        ],
                    },
                ],
            },
            {
                id: 'gemini-deep-dive',
                title: 'Understanding Gemini',
                intro: 'Google\'s flagship AI and how it connects everything.',
                cards: [
                    {
                        id: 'slide-gemini',
                        type: 'slideViewer',
                        title: 'Gemini: The Infrastructure Skill',
                        pdfPath: '/slides/3. Gemini_The_Infrastructure_Skill.pdf',
                    },
                ],
            },
            {
                id: 'role-use-cases',
                title: 'Real-World AI Use Cases by Role',
                intro: 'Click any card to see how AI transforms real work scenarios with specific tools and workflows.',
                cards: [
                    {
                        id: 'role-cases-grid',
                        type: 'roleUseCases',
                        fullWidth: true,
                        roleUseCases: [
                            {
                                role: 'Sales',
                                scenario: 'Qualify 200 inbound leads from a trade show overnight',
                                tools: [
                                    { name: 'Gemini API', usesCredits: true },
                                    { name: 'BigQuery', usesCredits: true },
                                    { name: 'Sheets' },
                                ],
                                workflow: [
                                    'Import leads CSV to BigQuery for structured analysis',
                                    'Use Gemini to analyze company data and score leads 1-10',
                                    'Auto-generate personalized follow-up email drafts',
                                    'Export prioritized list with talking points to CRM',
                                ],
                                result: '8 hours of manual work done in 30 minutes',
                                primaryUrl: 'https://cloud.google.com/bigquery',
                            },
                            {
                                role: 'Marketing',
                                scenario: 'Create 10 video ads for different audience segments',
                                tools: [
                                    { name: 'Veo 3', usesCredits: true },
                                    { name: 'HeyGen' },
                                    { name: 'Gemini' },
                                ],
                                workflow: [
                                    'Generate 10 script variations with Gemini (different tones per segment)',
                                    'Create AI avatar spokesperson with HeyGen',
                                    'Generate cinematic B-roll footage with Veo 3',
                                    'Combine and export for each platform',
                                ],
                                result: '3-week production cycle reduced to 2 days',
                                primaryUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview',
                            },
                            {
                                role: 'Project Manager',
                                scenario: 'Summarize 50 pages of stakeholder feedback into action items',
                                tools: [
                                    { name: 'NotebookLM' },
                                    { name: 'Gemini' },
                                    { name: 'Sheets' },
                                ],
                                workflow: [
                                    'Upload all feedback documents to NotebookLM',
                                    'Ask: "Extract all action items with owner and deadline"',
                                    'Generate an audio podcast summary for the team',
                                    'Export structured action items to Sheets',
                                ],
                                result: '4 hours of reading reduced to 10 minutes',
                                primaryUrl: 'https://notebooklm.google.com/',
                            },
                            {
                                role: 'Customer Support',
                                scenario: 'Handle 500 support tickets after a product launch',
                                tools: [
                                    { name: 'Vertex AI Agent Builder', usesCredits: true },
                                    { name: 'Gemini', usesCredits: true },
                                ],
                                workflow: [
                                    'Train an agent on product docs and common issues',
                                    'Auto-categorize incoming tickets by urgency and type',
                                    'Generate draft responses for agent review',
                                    'Escalate complex issues with full context summaries',
                                ],
                                result: '15 min per ticket reduced to 2 min per ticket',
                                primaryUrl: 'https://cloud.google.com/products/agent-builder',
                            },
                            {
                                role: 'Finance',
                                scenario: 'Explain quarterly results to non-finance stakeholders',
                                tools: [
                                    { name: 'Gemini' },
                                    { name: 'Gamma.app' },
                                    { name: 'Sheets' },
                                ],
                                workflow: [
                                    'Upload financial data to Gemini for analysis',
                                    'Ask: "Explain these results like I am a sales manager"',
                                    'Generate visual presentation with Gamma',
                                    'Create FAQ document for common questions',
                                ],
                                result: 'Complex finance translated to clear narrative',
                                primaryUrl: 'https://gemini.google.com/',
                            },
                            {
                                role: 'HR',
                                scenario: 'Screen 300 resumes for 5 open positions',
                                tools: [
                                    { name: 'Gemini', usesCredits: true },
                                    { name: 'Sheets' },
                                    { name: 'Vertex AI', usesCredits: true },
                                ],
                                workflow: [
                                    'Define specific criteria and must-haves per role',
                                    'Use Gemini to score and rank candidates objectively',
                                    'Generate tailored interview questions per candidate',
                                    'Create bias-check report for review',
                                ],
                                result: '2 weeks of screening done in 4 hours',
                                primaryUrl: 'https://cloud.google.com/vertex-ai',
                            },
                        ],
                    },
                ],
            },
            {
                id: 'case-study',
                title: 'Case Study: From Idea to Product Demo in One Day',
                intro: 'See how a founder combined multiple AI tools to create a professional product demo video with $0 budget.',
                cards: [
                    {
                        id: 'founder-case-study',
                        type: 'caseStudy',
                        fullWidth: true,
                        caseStudy: {
                            title: 'Launch an AI-Powered Product Demo Video',
                            context: 'A startup founder needs a professional product demo video for investors. No budget for a production crew, no time to hire freelancers.',
                            steps: [
                                {
                                    time: '8:00 AM',
                                    title: 'Script Writing',
                                    description: 'Prompt Gemini to write a 60-second product demo script. Iterate through 3 versions, pick the best and refine the tone.',
                                    tools: [{ name: 'Gemini' }],
                                },
                                {
                                    time: '9:00 AM',
                                    title: 'UI Mockups',
                                    description: 'Use Google Stitch to generate professional UI mockups from text descriptions. Export as high-res images.',
                                    tools: [{ name: 'Google Stitch', usesCredits: true }],
                                },
                                {
                                    time: '10:00 AM',
                                    title: 'Avatar Video',
                                    description: 'Upload script to HeyGen, choose a professional avatar, generate video in 3 languages for global reach.',
                                    tools: [{ name: 'HeyGen' }],
                                },
                                {
                                    time: '11:00 AM',
                                    title: 'B-Roll Generation',
                                    description: 'Use Veo 3 to generate tech-themed footage and abstract AI visuals. Download 5 clips for editing.',
                                    tools: [{ name: 'Veo 3', usesCredits: true }],
                                },
                                {
                                    time: '12:00 PM',
                                    title: 'Video Assembly',
                                    description: 'Combine all assets in any video editor. Add music, transitions, and export for web and social.',
                                    tools: [{ name: 'Any Editor' }],
                                },
                                {
                                    time: '2:00 PM',
                                    title: 'Investor Prep',
                                    description: 'Upload product docs to NotebookLM, generate investor FAQ, create audio summary for team prep.',
                                    tools: [{ name: 'NotebookLM' }],
                                },
                            ],
                            outcome: {
                                summary: 'Professional product demo video that would traditionally cost $5,000-10,000 and take 2-4 weeks.',
                                traditional: '$5,000+ and 2-4 weeks',
                                withAI: '$0 and 1 day',
                            },
                        },
                    },
                ],
            },
        ],
    },

    // ===== TAB 3: FREE COURSES =====
    {
        id: 'free-courses',
        label: 'Free Courses',
        hero: {
            title: 'Free AI Education',
            subtitle: 'High-quality courses you can start right now, at no cost.',
            videoUrl: 'https://www.youtube.com/embed/G2fqAlgmoPo',
        },
        sections: [
            {
                id: 'google-free',
                title: 'Google Cloud Skills Boost',
                intro: 'Earn badges for your resume while learning AI fundamentals. Uses your free monthly points.',
                cards: [
                    {
                        id: 'intro-gen-ai',
                        type: 'courseCard',
                        title: 'Introduction to Generative AI',
                        provider: 'Google',
                        duration: '45 mins',
                        level: 'beginner',
                        content: 'Learn what Generative AI is, how it works, and how it differs from traditional ML. Perfect first course for beginners.',
                        url: 'https://www.cloudskillsboost.google/course_templates/536',
                    },
                    {
                        id: 'gemini-workspace',
                        type: 'courseCard',
                        title: 'Google Workspace with Gemini',
                        provider: 'Google',
                        duration: '2 hours',
                        level: 'beginner',
                        content: 'Master using Gemini in Gmail, Docs, Sheets, and Slides for 10x productivity in your daily work.',
                        url: 'https://www.cloudskillsboost.google/paths/249',
                    },
                    {
                        id: 'gen-ai-leader',
                        type: 'courseCard',
                        title: 'Generative AI for Leaders',
                        provider: 'Google',
                        duration: '3 hours',
                        level: 'beginner',
                        content: 'For managers: understand how to lead AI initiatives in your organization.',
                        url: 'https://www.cloudskillsboost.google/paths/118',
                    },
                    {
                        id: 'intro-llm',
                        type: 'courseCard',
                        title: 'Introduction to Large Language Models',
                        provider: 'Google',
                        duration: '30 mins',
                        level: 'beginner',
                        content: 'Understand how LLMs work and their use cases across industries.',
                        url: 'https://www.cloudskillsboost.google/course_templates/539',
                    },
                ],
            },
            {
                id: 'other-free',
                title: 'More Free Resources',
                intro: 'High-quality free courses from other industry leaders.',
                cards: [
                    {
                        id: 'ai-for-everyone',
                        type: 'courseCard',
                        title: 'AI For Everyone',
                        provider: 'DeepLearning.AI',
                        duration: '4 weeks',
                        level: 'beginner',
                        content: 'Andrew Ng\'s famous course. No coding required. Understand what AI can and cannot do.',
                        url: 'https://www.coursera.org/learn/ai-for-everyone',
                    },
                    {
                        id: 'fast-ai',
                        type: 'courseCard',
                        title: 'Practical Deep Learning',
                        provider: 'fast.ai',
                        duration: 'Self-paced',
                        level: 'intermediate',
                        content: 'For those who want hands-on coding. Build real AI models from day one.',
                        url: 'https://course.fast.ai/',
                    },
                    {
                        id: 'kaggle-learn',
                        type: 'courseCard',
                        title: 'Kaggle Learn',
                        provider: 'Kaggle',
                        duration: 'Self-paced',
                        level: 'beginner',
                        content: 'Free micro-courses on Python, ML, and data science. Great for hands-on practice.',
                        url: 'https://www.kaggle.com/learn',
                    },
                    {
                        id: 'microsoft-ai',
                        type: 'courseCard',
                        title: 'AI Fundamentals',
                        provider: 'Microsoft Learn',
                        duration: '5 hours',
                        level: 'beginner',
                        content: 'Prepare for the Azure AI Fundamentals certification. Free learning path.',
                        url: 'https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/',
                    },
                ],
            },
        ],
    },

    // ===== TAB 4: CERTIFICATES =====
    {
        id: 'certificates',
        label: 'Certificates',
        hero: {
            title: 'Courses & Credentials',
            subtitle: 'Investment-based learning with certificates for your resume.',
            videoUrl: 'https://www.youtube.com/embed/5NgNicANyqM',
        },
        sections: [
            {
                id: 'career-slide',
                title: 'Why Invest in AI Education?',
                cards: [
                    {
                        id: 'slide-career',
                        type: 'slideViewer',
                        title: 'Future-Proofing Your Career',
                        pdfPath: '/slides/2. AI_Imperative_Future_Proofing_Your_Career.pdf',
                    },
                ],
            },
            {
                id: 'recommended-courses',
                title: 'Recommended Learning Path',
                intro: 'All courses below are included with Coursera Plus (50% off until Jan 26 - just $100/year). If you are dedicated, you could complete all 6 courses in 1-2 months and have certificates to add to your resume.',
                centered: true,
                cards: [
                    {
                        id: 'coursera-link',
                        type: 'alert',
                        alertType: 'tip',
                        title: 'Get Coursera Plus - 50% Off',
                        content: 'Coursera Plus gives you unlimited access to all courses below. Annual: $100 (normally $200). Monthly: $20 (40% off). Get started now.',
                        fullWidth: true,
                    },
                    {
                        id: 'prompting-essentials',
                        type: 'courseCard',
                        title: 'Google Prompting Essentials',
                        provider: 'Google',
                        duration: '4 hours',
                        price: 'Included',
                        level: 'beginner',
                        content: 'Master the art of prompting. Learn to get exactly what you need from AI assistants.',
                        url: 'https://www.coursera.org/learn/google-prompting-essentials',
                    },
                    {
                        id: 'ai-essentials',
                        type: 'courseCard',
                        title: 'Google AI Essentials',
                        provider: 'Google',
                        duration: '4 weeks',
                        price: 'Included',
                        level: 'beginner',
                        content: 'Comprehensive AI fundamentals: productivity tools, responsible AI, staying current.',
                        url: 'https://www.coursera.org/learn/google-ai-essentials',
                    },
                    {
                        id: 'intro-ml',
                        type: 'courseCard',
                        title: 'Introduction to AI and Machine Learning',
                        provider: 'Google Cloud',
                        duration: '8 hours',
                        price: 'Included',
                        level: 'beginner',
                        content: 'Technical introduction to how AI and ML actually work under the hood.',
                        url: 'https://www.coursera.org/learn/introduction-to-ai-and-machine-learning-on-google-cloud',
                    },
                    {
                        id: 'claude-code',
                        type: 'courseCard',
                        title: 'Claude Code In Action',
                        provider: 'Anthropic',
                        duration: '2 hours',
                        price: 'Included',
                        level: 'beginner',
                        content: 'Learn to use Claude for coding assistance and complex reasoning tasks.',
                        url: 'https://www.coursera.org/learn/claude-code-in-action',
                    },
                    {
                        id: 'mcp-intro',
                        type: 'courseCard',
                        title: 'Introduction to Model Context Protocol',
                        provider: 'Anthropic',
                        duration: '3 hours',
                        price: 'Included',
                        level: 'intermediate',
                        content: 'Understand the future of AI integration with MCP - how AI connects to tools.',
                        url: 'https://www.coursera.org/learn/introduction-to-model-context-protocol-mcp',
                    },
                ],
            },
            {
                id: 'official-certs',
                title: 'Advanced: Official Google Certification',
                intro: 'Proctored exams for those who want industry-recognized credentials. Best for non-technical professionals wanting to demonstrate cloud understanding.',
                cards: [
                    {
                        id: 'cdl-cert',
                        type: 'courseCard',
                        title: 'Cloud Digital Leader',
                        provider: 'Google Cloud',
                        duration: '10-20 hours study',
                        price: '$99 exam',
                        level: 'beginner',
                        content: 'Entry-level certification. Perfect for sales, PM, consulting, or business roles. Shows you understand cloud concepts without requiring technical depth. Easy to obtain but still respected.',
                        url: 'https://cloud.google.com/learn/certification/cloud-digital-leader',
                    },
                ],
            },
            {
                id: 'financial-aid',
                title: 'Need Financial Aid?',
                intro: 'Coursera offers financial aid for most courses if you cannot afford the subscription.',
                cards: [
                    {
                        id: 'aid-video',
                        type: 'videoEmbed',
                        title: 'How to Apply for Financial Aid',
                        videoId: 'https://www.youtube.com/watch?v=11MwVZcyG6c',
                    },
                    {
                        id: 'aid-tip',
                        type: 'alert',
                        alertType: 'tip',
                        title: 'Application Tips',
                        content: 'Financial aid applications take up to 14 days for approval. Be honest about your financial situation. Most applications are approved! You apply for each specific course, not the entire platform.',
                    },
                ],
            },
        ],
    },

    // ===== TAB 5: AI TOOLS =====
    {
        id: 'ai-tools',
        label: 'AI Tools',
        hero: {
            title: 'Essential AI Tools',
            subtitle: 'The best tools to supercharge your workflow.',
            videoUrl: 'https://www.youtube.com/embed/zy8n-gGgonk',
        },
        sections: [
            {
                id: 'credits-reminder',
                title: '',
                cards: [
                    {
                        id: 'credits-callout',
                        type: 'alert',
                        alertType: 'tip',
                        title: 'Use Your $300 Google Cloud Credits!',
                        content: 'Tools marked with a $ badge below can be accessed using your free $300 Google Cloud credits. Sign up at console.cloud.google.com to claim yours.',
                        fullWidth: true,
                    },
                ],
            },
            {
                id: 'video-creation',
                title: 'Video Creation',
                intro: 'Create professional videos without cameras or crews.',
                cards: [
                    {
                        id: 'veo3',
                        type: 'toolCard',
                        title: 'Veo 3 ($300)',
                        content: 'Google\'s text-to-video AI. Generate cinematic footage with synchronized audio from text prompts. Available via Vertex AI - uses your $300 credits.',
                        url: 'https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview',
                        iconPath: '/icons/video.svg',
                    },
                    {
                        id: 'heygen',
                        type: 'toolCard',
                        title: 'HeyGen',
                        content: 'Create AI avatar spokesperson videos. Upload a script, choose an avatar, get a professional video in minutes. 175+ languages.',
                        url: 'https://heygen.com',
                        iconPath: '/icons/ai.svg',
                    },
                    {
                        id: 'higgsfield',
                        type: 'toolCard',
                        title: 'Higgsfield',
                        content: 'Transform static images into cinematic video clips. Upload a photo, get a 3-5 second animated video with realistic motion.',
                        url: 'https://higgsfield.ai',
                        iconPath: '/icons/lightning.svg',
                    },
                    {
                        id: 'nanabanana',
                        type: 'toolCard',
                        title: 'Nano Banana',
                        content: 'Quick image-to-video conversion. Describe camera movements and motion, AI adds natural movement and effects.',
                        url: 'https://nanabanana.io',
                        iconPath: '/icons/startup.svg',
                    },
                ],
            },
            {
                id: 'productivity-tools',
                title: 'Productivity Essentials',
                intro: 'Tools that will 10x your daily output.',
                cards: [
                    {
                        id: 'superwhisper',
                        type: 'toolCard',
                        title: 'Superwhisper',
                        content: 'AI-powered voice to text for Mac. Write 3x faster by speaking. 150 WPM speaking vs 60-80 WPM typing. Runs locally, 100% private.',
                        url: 'https://superwhisper.com',
                        statImage: '/dication.png',
                    },
                    {
                        id: 'notebooklm',
                        type: 'toolCard',
                        title: 'NotebookLM',
                        content: 'Google\'s AI research assistant. Upload documents, get summaries, ask questions, even generate podcasts from your content.',
                        url: 'https://notebooklm.google.com',
                        iconPath: '/icons/book.svg',
                    },
                    {
                        id: 'perplexity',
                        type: 'toolCard',
                        title: 'Perplexity AI',
                        content: 'AI-powered search engine with citations. Perfect for research and fact-checking. Better than Google for many queries.',
                        url: 'https://perplexity.ai',
                        iconPath: '/icons/speedometer.svg',
                    },
                    {
                        id: 'otter',
                        type: 'toolCard',
                        title: 'Otter.ai',
                        content: 'Meeting transcription and notes. Automatically transcribes meetings and generates summaries. Integrates with Zoom.',
                        url: 'https://otter.ai',
                        iconPath: '/icons/headphones.svg',
                    },
                ],
            },
            {
                id: 'ai-assistants',
                title: 'AI Assistants',
                intro: 'Your AI conversation partners.',
                cards: [
                    {
                        id: 'gemini',
                        type: 'toolCard',
                        title: 'Gemini',
                        content: 'Google\'s flagship AI. Integrated into Workspace. Great for analysis, creative work, and daily tasks.',
                        url: 'https://gemini.google.com',
                        iconPath: '/icons/ai.svg',
                    },
                    {
                        id: 'claude',
                        type: 'toolCard',
                        title: 'Claude',
                        content: 'Anthropic\'s AI. Excellent for long-form writing, analysis, and coding. Best for nuanced, thoughtful responses.',
                        url: 'https://claude.ai',
                        iconPath: '/icons/artificial-intelligence.svg',
                    },
                    {
                        id: 'ai-studio',
                        type: 'toolCard',
                        title: 'Google AI Studio ($300)',
                        content: 'The fastest path from prompt to production. Experiment with Gemini, tune prompts, get API keys. Uses your $300 credits.',
                        url: 'https://aistudio.google.com',
                        iconPath: '/icons/lightning.svg',
                    },
                ],
            },
            {
                id: 'developer-tools',
                title: 'Design & Developer Tools',
                intro: 'Create interfaces and code with AI assistance.',
                cards: [
                    {
                        id: 'stitch',
                        type: 'toolCard',
                        title: 'Google Stitch ($300)',
                        content: 'AI UI design to production code. Describe your interface in plain English, get React/HTML/CSS code. Uses your $300 credits.',
                        url: 'https://stitch.withgoogle.com/',
                        iconPath: '/icons/diamond.svg',
                    },
                    {
                        id: 'cursor',
                        type: 'toolCard',
                        title: 'Cursor',
                        content: 'AI-first code editor. Write code by describing what you want. Great for learning to code with AI assistance.',
                        url: 'https://cursor.sh',
                        iconPath: '/icons/coding.svg',
                    },
                    {
                        id: 'opencode',
                        type: 'toolCard',
                        title: 'OpenCode',
                        content: 'Open-source AI coding assistant. Terminal-based, works with any LLM. Great for developers who want full control.',
                        url: 'https://github.com/AquariniqueMu/opencode',
                        iconPath: '/icons/coding.svg',
                    },
                    {
                        id: 'v0',
                        type: 'toolCard',
                        title: 'v0.dev',
                        content: 'Generate UI components from text descriptions. Create beautiful interfaces without design skills.',
                        url: 'https://v0.dev',
                        iconPath: '/icons/startup.svg',
                    },
                    {
                        id: 'gamma',
                        type: 'toolCard',
                        title: 'Gamma.app',
                        content: 'AI-powered presentations. Create beautiful slides in minutes just by describing what you want.',
                        url: 'https://gamma.app',
                        iconPath: '/icons/diamond.svg',
                    },
                ],
            },
            {
                id: 'ai-infrastructure',
                title: 'AI Infrastructure & Agents',
                intro: 'Advanced tools for building and managing AI systems.',
                cards: [
                    {
                        id: 'vertex',
                        type: 'toolCard',
                        title: 'Vertex AI ($300)',
                        content: 'Google\'s enterprise ML platform. Build, deploy, and scale AI models. Agent Builder for creating AI assistants. Uses $300 credits.',
                        url: 'https://cloud.google.com/vertex-ai',
                        iconPath: '/icons/cloud-network.svg',
                    },
                    {
                        id: 'antigravity',
                        type: 'toolCard',
                        title: 'Antigravity',
                        content: 'AI agent rule ecosystem. Standardized rules and protocols for AI agents. The Bridge Protocol for agent collaboration.',
                        url: 'https://github.com/Antigravity-Research/Rules',
                        iconPath: '/icons/ai.svg',
                    },
                    {
                        id: 'beads',
                        type: 'toolCard',
                        title: 'Beads (Steve Yegge)',
                        content: 'Memory system for AI coding agents. Solves the "50 First Dates" problem - agents remember previous sessions.',
                        url: 'https://github.com/steveyegge/beads',
                        iconPath: '/icons/artificial-intelligence.svg',
                    },
                    {
                        id: 'ralph-loop',
                        type: 'toolCard',
                        title: 'Ralph Loop',
                        content: 'Agent iteration pattern. Keeps AI agents working on tasks until complete. Used by Vercel, Goose, and Letta Code.',
                        url: 'https://github.com/vercel-labs/ralph-loop-agent',
                        iconPath: '/icons/speedometer.svg',
                    },
                ],
            },
        ],
    },
];
